/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedFocusRouteImport } from './routes/_authenticated/focus'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedNotesTextRouteImport } from './routes/_authenticated/notes.text'
import { Route as AuthenticatedNotesSpeechRouteImport } from './routes/_authenticated/notes.speech'
import { Route as AuthenticatedNotesIdRouteImport } from './routes/_authenticated/notes.$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFocusRoute = AuthenticatedFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesTextRoute = AuthenticatedNotesTextRouteImport.update({
  id: '/text',
  path: '/text',
  getParentRoute: () => AuthenticatedNotesRoute,
} as any)
const AuthenticatedNotesSpeechRoute =
  AuthenticatedNotesSpeechRouteImport.update({
    id: '/speech',
    path: '/speech',
    getParentRoute: () => AuthenticatedNotesRoute,
  } as any)
const AuthenticatedNotesIdRoute = AuthenticatedNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedNotesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/notes': typeof AuthenticatedNotesRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/notes/$id': typeof AuthenticatedNotesIdRoute
  '/notes/speech': typeof AuthenticatedNotesSpeechRoute
  '/notes/text': typeof AuthenticatedNotesTextRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/focus': typeof AuthenticatedFocusRoute
  '/notes': typeof AuthenticatedNotesRouteWithChildren
  '/tasks': typeof AuthenticatedTasksRoute
  '/notes/$id': typeof AuthenticatedNotesIdRoute
  '/notes/speech': typeof AuthenticatedNotesSpeechRoute
  '/notes/text': typeof AuthenticatedNotesTextRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/focus': typeof AuthenticatedFocusRoute
  '/_authenticated/notes': typeof AuthenticatedNotesRouteWithChildren
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/notes/$id': typeof AuthenticatedNotesIdRoute
  '/_authenticated/notes/speech': typeof AuthenticatedNotesSpeechRoute
  '/_authenticated/notes/text': typeof AuthenticatedNotesTextRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/focus'
    | '/notes'
    | '/tasks'
    | '/notes/$id'
    | '/notes/speech'
    | '/notes/text'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/focus'
    | '/notes'
    | '/tasks'
    | '/notes/$id'
    | '/notes/speech'
    | '/notes/text'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/_authenticated/focus'
    | '/_authenticated/notes'
    | '/_authenticated/tasks'
    | '/_authenticated/notes/$id'
    | '/_authenticated/notes/speech'
    | '/_authenticated/notes/text'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/focus': {
      id: '/_authenticated/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof AuthenticatedFocusRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes/text': {
      id: '/_authenticated/notes/text'
      path: '/text'
      fullPath: '/notes/text'
      preLoaderRoute: typeof AuthenticatedNotesTextRouteImport
      parentRoute: typeof AuthenticatedNotesRoute
    }
    '/_authenticated/notes/speech': {
      id: '/_authenticated/notes/speech'
      path: '/speech'
      fullPath: '/notes/speech'
      preLoaderRoute: typeof AuthenticatedNotesSpeechRouteImport
      parentRoute: typeof AuthenticatedNotesRoute
    }
    '/_authenticated/notes/$id': {
      id: '/_authenticated/notes/$id'
      path: '/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof AuthenticatedNotesIdRouteImport
      parentRoute: typeof AuthenticatedNotesRoute
    }
  }
}

interface AuthenticatedNotesRouteChildren {
  AuthenticatedNotesIdRoute: typeof AuthenticatedNotesIdRoute
  AuthenticatedNotesSpeechRoute: typeof AuthenticatedNotesSpeechRoute
  AuthenticatedNotesTextRoute: typeof AuthenticatedNotesTextRoute
}

const AuthenticatedNotesRouteChildren: AuthenticatedNotesRouteChildren = {
  AuthenticatedNotesIdRoute: AuthenticatedNotesIdRoute,
  AuthenticatedNotesSpeechRoute: AuthenticatedNotesSpeechRoute,
  AuthenticatedNotesTextRoute: AuthenticatedNotesTextRoute,
}

const AuthenticatedNotesRouteWithChildren =
  AuthenticatedNotesRoute._addFileChildren(AuthenticatedNotesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFocusRoute: typeof AuthenticatedFocusRoute
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRouteWithChildren
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFocusRoute: AuthenticatedFocusRoute,
  AuthenticatedNotesRoute: AuthenticatedNotesRouteWithChildren,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
